FROM ubuntu:latest

# Define o diretório de trabalho dentro do contêiner
WORKDIR /app

# Instala as dependências
RUN apt-get update && apt-get install iputils-ping net-tools python3 python3-pip -y

# Copia o restante do código da aplicação
COPY servidorSincrono.py ./src/

EXPOSE 80

# Comando para iniciar a aplicacao do servidor sincrono
CMD ["python3", "/app/src/servidorSincrono.py"]