FROM ubuntu:latest

# Define o diretorio de trabalho dentro do conteiner
WORKDIR /app

# Instala as dependencias
RUN apt update && apt install iputils-ping net-tools python3 python3-pip -y

# Copia o restante do codigo da aplicacao
COPY servidorAssincrono.py ./src/

EXPOSE 80

# Comando para iniciar a aplicacao do servidor assincrono
CMD ["python3", "/app/src/servidorAssincrono.py"]