FROM python:3.9-slim
# Define o diretorio de trabalho dentro do conteiner
WORKDIR /app

# Instala as dependencias
RUN apt-get update && apt-get install -y \
    iputils-ping \
    net-tools \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    requests \
    matplotlib \
    pandas \
    numpy
# Copia o restante do codigo da aplicacao
COPY . /app

# Comandos para iniciar o cliente e executar os testes e gerar resultados
CMD ["tail", "-f", "/dev/null"]