FROM grafana/grafana:latest

ENV GF_SECURITY_ADMIN_PASSWORD=admin
ENV GF_SECURITY_ADMIN_USER=admin

COPY datasources.yml /etc/grafana/provisioning/datasources/datasources.yml
COPY dashboards.yml /etc/grafana/provisioning/dashboards/dashboards.yml
COPY dashboards/ /etc/grafana/provisioning/dashboards/

EXPOSE 3000

CMD ["grafana-server", "--config=/etc/grafana/grafana.ini"]
