# Usa a imagem oficial do Apache
FROM httpd:latest

# Define diretório de trabalho
WORKDIR /usr/local/apache2

# Copia os arquivos HTML para o DocumentRoot
COPY html/ /usr/local/apache2/htdocs/

# Copia configuração customizada do Apache
COPY httpd.conf /usr/local/apache2/conf/httpd.conf

# Expõe a porta padrão do Apache
EXPOSE 80
